---
- hosts: db
  name: db servers
  become: yes

  vars_files:
    - vars/main.yml

#  pre_tasks:
#    - name: Remove the Apache test page.
    

  roles:
- roles/bonis.debug
#    - roles/geerlingguy.repo-epel
#    - roles/geerlingguy.firewall
#    - roles/oracle
#    - roles/oracle-dump

  tasks:
    include: tasks/main.yml



#  pos_tasks:
#    - name: Remove the Apache test page.
#      file:
#        path: /var/www/html/index.html
#        state: absent
#    - name: Copy our fancy server-specific home page.
#      template:
#        src: templates/index.php.j2
#        dest: /var/www/html/index.php